CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    name  VARCHAR(100)                                   NOT NULL,
    email VARCHAR(100)                                   NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY                NOT NULL,
    description VARCHAR(200)                                          NOT NULL,
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE                               NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY                       NOT NULL,
    name  VARCHAR(100)                                                    NOT NULL,
    description  VARCHAR(200)                                             NOT NULL,
    available  BOOLEAN                                                    NOT NULL,
    owner_id  BIGINT REFERENCES users (user_id) ON DELETE CASCADE         NOT NULL,
    request_id BIGINT REFERENCES requests (request_id) ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY            NOT NULL,
    text  VARCHAR(200)                                            NOT NULL,
    item_id  BIGINT REFERENCES items (item_id) ON DELETE CASCADE  NOT NULL,
    author_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE                           NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY              NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE                          NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE                            NOT NULL,
    item_id    BIGINT REFERENCES items (item_id) ON DELETE CASCADE  NOT NULL,
    booker_id  BIGINT REFERENCES users (user_id) ON DELETE CASCADE  NOT NULL,
    status VARCHAR(10)                                              NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

