CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    name  VARCHAR(100)                                   NOT NULL,
    email VARCHAR(100)                                   NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    name  VARCHAR(100)                                   NOT NULL,
    description  VARCHAR(200)                            NOT NULL,
    available  BOOLEAN                                   NOT NULL,
    owner_id  BIGINT REFERENCES users (user_id)          NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    text  VARCHAR(200)                                      NOT NULL,
    item_id  BIGINT REFERENCES items (item_id)              NOT NULL,
    author_id BIGINT REFERENCES users (user_id)             NOT NULL,
    created TIMESTAMP WITH TIME ZONE                        NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE                  NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    item_id    BIGINT REFERENCES items (item_id)            NOT NULL,
    booker_id  BIGINT REFERENCES users (user_id)            NOT NULL,
    status VARCHAR(10)                                      NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

